### ISSUE TITLE
Home Assistant 2021.6.0 breaks this

### ISSUE THREAD

**Issue by trentjw** [toreamun/victorsmartkill-homeassistant#6]
## Configuration

```yaml

Logger: homeassistant.setup
Source: setup.py:172
First occurred: 10:01:47 PM (1 occurrences)
Last logged: 10:01:47 PM

Setup failed for victorsmartkill: Integration not found.

```

## Debug log

```text

Add your logs here.

```
